import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1771839488882 implements MigrationInterface {
    name = 'InitialSchema1771839488882'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_machine" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "machineId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_af72a60760d2af7032bae47e7bb" UNIQUE ("userId", "machineId"), CONSTRAINT "PK_4c1e4543d4b1888dd3a7975993c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "machine" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "status" boolean NOT NULL DEFAULT true, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c60541d21fe9d462cb49752d7de" UNIQUE ("name"), CONSTRAINT "PK_acc588900ffa841d96eb5fd566c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unit_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "constant" boolean NOT NULL, "constantValue" double precision NOT NULL, CONSTRAINT "UQ_0f1d312e5d4ae66ad45b76e0a1c" UNIQUE ("name"), CONSTRAINT "PK_712ecbc07fd22c595283395f4c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "operator_stock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "itemId" uuid NOT NULL, "quantity" integer NOT NULL, "description" character varying, "status" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "uomId" uuid NOT NULL, "baseUomId" character varying NOT NULL, "unit" double precision NOT NULL, CONSTRAINT "PK_c713960661899bf90d92a8818e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "status" boolean NOT NULL DEFAULT true, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_019d74f7abcdcb5a0113010cb03" UNIQUE ("name"), CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "non_stock_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "status" boolean NOT NULL DEFAULT true, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3b75de8d0754fcdb8fe52271b38" UNIQUE ("name"), CONSTRAINT "PK_dc40d2344627972948e1f532627" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pricing" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "itemId" uuid NOT NULL, "serviceId" uuid, "nonStockServiceId" uuid, "isNonStockService" boolean NOT NULL DEFAULT false, "sellingPrice" double precision NOT NULL, "costPrice" double precision NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "constant" boolean NOT NULL DEFAULT false, "height" double precision, "width" double precision, "baseUomId" uuid NOT NULL, CONSTRAINT "PK_4f6e9c88033106a989aa7ce9dee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_item_note" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "text" character varying NOT NULL, "userId" uuid NOT NULL, "date" TIMESTAMP NOT NULL, "hour" TIMESTAMP NOT NULL, "purchaseItemId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2a5b4134bd986f6d00c4cbd5491" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71f033720e65d50b1fc466b5f4" ON "purchase_item_note" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c8130ad301f2928a23ff2ca369" ON "purchase_item_note" ("purchaseItemId") `);
        await queryRunner.query(`CREATE TABLE "purchase_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchaseId" uuid NOT NULL, "itemId" uuid NOT NULL, "quantity" integer NOT NULL, "unitPrice" double precision NOT NULL, "amount" double precision NOT NULL, "description" character varying, "status" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "uomId" uuid NOT NULL, "baseUomId" character varying NOT NULL, "unit" double precision NOT NULL, CONSTRAINT "UQ_b51a9c31b0f4f07ed2ac39ef271" UNIQUE ("purchaseId", "itemId"), CONSTRAINT "PK_e3d9bea880baad86ff6de3290da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "series" character varying NOT NULL, "operatorId" uuid NOT NULL, "status" character varying NOT NULL, "orderDate" TIMESTAMP NOT NULL DEFAULT now(), "note" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "totalQuantity" integer NOT NULL, CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales_item_note" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "text" character varying NOT NULL, "userId" uuid NOT NULL, "date" TIMESTAMP NOT NULL, "hour" TIMESTAMP NOT NULL, "saleItemId" uuid NOT NULL, CONSTRAINT "PK_6ec0d1c8aff78bd0f144efde8a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fdacec9dee011f00cf271c0d98" ON "sales_item_note" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f31014ee602711ef7855df1db" ON "sales_item_note" ("saleItemId") `);
        await queryRunner.query(`CREATE TABLE "sale_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "saleId" uuid NOT NULL, "itemId" uuid NOT NULL, "quantity" integer NOT NULL, "description" character varying, "status" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "uomId" uuid NOT NULL, "baseUomId" character varying NOT NULL, "unit" double precision NOT NULL, CONSTRAINT "PK_5a7dc5b4562a9e590528b3e08ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "uom" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "abbreviation" character varying NOT NULL, "conversionRate" double precision NOT NULL, "baseUnit" boolean NOT NULL DEFAULT false, "unitCategoryId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0246fd4beee9bba40f4018bbcf0" UNIQUE ("name", "abbreviation", "unitCategoryId"), CONSTRAINT "PK_87729daf4a43ad4efdbdef69ff9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attribute" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "value" character varying NOT NULL, "itemId" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "itemsId" uuid, CONSTRAINT "UQ_350fb4f7eb87e4c7d35c97a9828" UNIQUE ("name"), CONSTRAINT "UQ_34d21f61011653902cfbb8b55b1" UNIQUE ("name", "itemId"), CONSTRAINT "PK_b13fb7c5c9e9dff62b60e0de729" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "discounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "level" integer NOT NULL, "itemId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "percentage" double precision NOT NULL, "unit" double precision NOT NULL, "description" character varying, CONSTRAINT "UQ_e1dd05494f9be96cb12620eeeb5" UNIQUE ("itemId", "level"), CONSTRAINT "PK_66c522004212dc814d6e2f14ecc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "reorder_level" integer NOT NULL, "initial_stock" integer NOT NULL, "updated_initial_stock" integer NOT NULL, "machineId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "can_be_purchased" boolean NOT NULL DEFAULT true, "can_be_sold" boolean NOT NULL DEFAULT true, "quantity" integer NOT NULL, "unitCategoryId" uuid, "defaultUomId" uuid, "purchaseUomId" uuid, CONSTRAINT "UQ_213736582899b3599acaade2cd1" UNIQUE ("name"), CONSTRAINT "PK_ba5885359424c15ca6b9e79bcf6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fullName" character varying NOT NULL, "email" character varying, "phone" character varying NOT NULL, "company" character varying, "address" character varying, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_88acd889fbe17d0e16cc4bc9174" UNIQUE ("phone"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commission_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" TIMESTAMP NOT NULL, "amount" double precision NOT NULL, "percentage" double precision NOT NULL, "commissionId" uuid NOT NULL, "paymentMethod" character varying NOT NULL, "reference" character varying NOT NULL, "status" character varying NOT NULL, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a9d68af7a671bb3aaa9d24b6272" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "salesPartnerId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "totalAmount" double precision NOT NULL, "paidAmount" double precision NOT NULL, CONSTRAINT "UQ_f5414c93004f4c88046110d9bd8" UNIQUE ("orderId"), CONSTRAINT "REL_f5414c93004f4c88046110d9bd" UNIQUE ("orderId"), CONSTRAINT "PK_2701379966e2e670bb5ff0ae78e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales_partners" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fullName" character varying NOT NULL, "email" character varying, "phone" character varying NOT NULL, "company" character varying, "address" character varying NOT NULL, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_792436093d2a7ae35f35ebb3b0b" UNIQUE ("email"), CONSTRAINT "UQ_26bdf5756431e7ca538a808d82c" UNIQUE ("phone"), CONSTRAINT "PK_b87824a53eb1ff2feb7d86c895a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" TIMESTAMP NOT NULL, "paymentTermId" uuid NOT NULL, "paymentMethod" character varying NOT NULL, "reference" character varying NOT NULL, "amount" double precision NOT NULL, "status" character varying NOT NULL, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d32b3c6b0d2c1d22604cbcc8c49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_terms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "totalAmount" double precision NOT NULL, "remainingAmount" double precision NOT NULL, "status" character varying NOT NULL, "forcePayment" boolean NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fc2ea9567ff5ab710909b61ec04" UNIQUE ("orderId"), CONSTRAINT "REL_fc2ea9567ff5ab710909b61ec0" UNIQUE ("orderId"), CONSTRAINT "PK_a7e7ab8cabd8982c57d817b7164" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "series" character varying NOT NULL, "customerId" uuid NOT NULL, "status" character varying NOT NULL, "orderDate" TIMESTAMP NOT NULL DEFAULT now(), "deliveryDate" TIMESTAMP NOT NULL, "totalAmount" double precision NOT NULL, "tax" double precision NOT NULL, "grandTotal" double precision NOT NULL, "totalQuantity" integer NOT NULL, "internalNote" character varying, "paymentTermId" character varying, "commissionId" character varying, "fileNames" text NOT NULL, "adminApproval" boolean NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "salesPartnersId" uuid, "orderSource" character varying NOT NULL, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "itemId" uuid NOT NULL, "serviceId" uuid, "nonStockServiceId" uuid, "isNonStockService" boolean NOT NULL DEFAULT false, "width" double precision, "height" double precision, "discount" double precision, "level" integer NOT NULL, "totalAmount" double precision NOT NULL, "adminApproval" boolean NOT NULL, "uomId" uuid NOT NULL, "quantity" integer NOT NULL, "unitPrice" double precision NOT NULL, "description" character varying, "status" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isDiscounted" boolean NOT NULL, "pricingId" uuid NOT NULL, "baseUomId" uuid NOT NULL, "unit" double precision NOT NULL, "totalCost" double precision NOT NULL DEFAULT '0', "sales" double precision NOT NULL DEFAULT '0', CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_item_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "text" character varying NOT NULL, "hour" TIMESTAMP NOT NULL, "date" TIMESTAMP NOT NULL, "userId" uuid NOT NULL, "orderItemId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dab2d378a2deb668de73ee299fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_roles_enum" AS ENUM('USER', 'ADMIN', 'RECEPTION', 'GRAPHIC_DESIGNER', 'OPERATOR', 'FINANCE', 'STORE_REPRESENTATIVE', 'PURCHASER')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "passwordRT" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "address" character varying NOT NULL, "first_name" character varying, "gender" character varying NOT NULL DEFAULT 'MALE', "last_name" character varying, "middle_name" character varying, "phone" character varying NOT NULL, "profile" character varying, "roles" "public"."user_roles_enum" NOT NULL DEFAULT 'ADMIN', "confirm_password" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_8e1f623798118e629b46a9e6299" UNIQUE ("phone"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "series" character varying NOT NULL, "vendorId" uuid NOT NULL, "status" character varying NOT NULL, "orderDate" TIMESTAMP NOT NULL DEFAULT now(), "paymentMethod" character varying NOT NULL, "amount" double precision NOT NULL, "reference" character varying NOT NULL, "totalAmount" double precision NOT NULL, "totalQuantity" integer NOT NULL, "note" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "purchaserId" uuid NOT NULL, CONSTRAINT "PK_1d55032f37a34c6eceacbbca6b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vendors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fullName" character varying NOT NULL, "email" character varying, "phone" character varying NOT NULL, "company" character varying, "address" character varying, "reference" character varying, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e1f64c741c359e588122ec92a66" UNIQUE ("fullName"), CONSTRAINT "UQ_67ab49bf11bb8ca309d54e5449f" UNIQUE ("phone"), CONSTRAINT "PK_9c956c9797edfae5c6ddacc4e6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fixed_cost" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "monthlyFixedCost" double precision NOT NULL, "dailyFixedCost" double precision NOT NULL, "description" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3824e1902668c6a065fe63be832" UNIQUE ("description"), CONSTRAINT "PK_b28c890cc8ad19d2bbc7bb037d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file_path" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "filePath" character varying NOT NULL, "fileType" character varying NOT NULL, "description" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c71ccdf7f5b3ab4d5abd99fc3b0" UNIQUE ("description"), CONSTRAINT "PK_f85ff4820b0c8f9d5068df9c8e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "services_items_items" ("servicesId" uuid NOT NULL, "itemsId" uuid NOT NULL, CONSTRAINT "PK_a46b05b0bcad3b3c51ba74e8e43" PRIMARY KEY ("servicesId", "itemsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_11e5c165b1866e0fe5dc2f5b17" ON "services_items_items" ("servicesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8d2d12b6b68b9da0d23b9aa72e" ON "services_items_items" ("itemsId") `);
        await queryRunner.query(`CREATE TABLE "items_services_services" ("itemsId" uuid NOT NULL, "servicesId" uuid NOT NULL, CONSTRAINT "PK_81ee83f254df6119b8874311897" PRIMARY KEY ("itemsId", "servicesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0af7ef64c6038062e767574dc8" ON "items_services_services" ("itemsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7864f4f5e2917fc23a6178ba7" ON "items_services_services" ("servicesId") `);
        await queryRunner.query(`ALTER TABLE "user_machine" ADD CONSTRAINT "FK_7f74ce92adc1bdbd3e525fbe8b7" FOREIGN KEY ("machineId") REFERENCES "machine"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_machine" ADD CONSTRAINT "FK_531514348ce1804ff125735acbc" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "operator_stock" ADD CONSTRAINT "FK_9f880821e14bcfc38e4fa152921" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "operator_stock" ADD CONSTRAINT "FK_f57c351323d17198f98203f7644" FOREIGN KEY ("uomId") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pricing" ADD CONSTRAINT "FK_bd8c383aa0df97a834c3fc77e83" FOREIGN KEY ("baseUomId") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pricing" ADD CONSTRAINT "FK_22aa7ee9e019f4f8bf61920da8c" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pricing" ADD CONSTRAINT "FK_420e1792e18656a1d66a20bab0c" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pricing" ADD CONSTRAINT "FK_399b0a2697e25f631095eaadd21" FOREIGN KEY ("nonStockServiceId") REFERENCES "non_stock_services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_item_note" ADD CONSTRAINT "FK_c8130ad301f2928a23ff2ca3697" FOREIGN KEY ("purchaseItemId") REFERENCES "purchase_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_item_note" ADD CONSTRAINT "FK_71f033720e65d50b1fc466b5f4a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_684a9853855f5edcd905dc2a9a8" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_8bafbb5d45827a5d25f5cd3c6f3" FOREIGN KEY ("purchaseId") REFERENCES "purchases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_items" ADD CONSTRAINT "FK_b7b4a9fd8cc9efa37d2488084bc" FOREIGN KEY ("uomId") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_bcfd467aaf89ac96018400368b7" FOREIGN KEY ("operatorId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_item_note" ADD CONSTRAINT "FK_3f31014ee602711ef7855df1dbc" FOREIGN KEY ("saleItemId") REFERENCES "sale_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_item_note" ADD CONSTRAINT "FK_fdacec9dee011f00cf271c0d98d" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_a22cb8ff5a4d3709da216b11610" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_c642be08de5235317d4cf3deb40" FOREIGN KEY ("saleId") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_e6f608e57a5ea871bbec9aa3521" FOREIGN KEY ("uomId") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uom" ADD CONSTRAINT "FK_999937e80f724f5a108f45af7bf" FOREIGN KEY ("unitCategoryId") REFERENCES "unit_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attribute" ADD CONSTRAINT "FK_3f57f0a2bd5fad53d34f1df877f" FOREIGN KEY ("itemsId") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discounts" ADD CONSTRAINT "FK_bd1d07c0a61acb7b03cc195509a" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_595a0c1018faf8f48c1ce36a280" FOREIGN KEY ("defaultUomId") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_9a4ea23f9a8c1e130d7d4c1ddad" FOREIGN KEY ("machineId") REFERENCES "machine"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_c59291c396d452f0c8e419d3e38" FOREIGN KEY ("purchaseUomId") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items" ADD CONSTRAINT "FK_629d91468f5a76f4472c4909261" FOREIGN KEY ("unitCategoryId") REFERENCES "unit_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commission_transactions" ADD CONSTRAINT "FK_f6fba111295cff46b676a143c0a" FOREIGN KEY ("commissionId") REFERENCES "commissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_f5414c93004f4c88046110d9bd8" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commissions" ADD CONSTRAINT "FK_6af6faa4f594d828c7e9b784595" FOREIGN KEY ("salesPartnerId") REFERENCES "sales_partners"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" ADD CONSTRAINT "FK_318578310d536d61d1d94f87fe7" FOREIGN KEY ("paymentTermId") REFERENCES "payment_terms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_terms" ADD CONSTRAINT "FK_fc2ea9567ff5ab710909b61ec04" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_510af4fb2333c7184d568099aa3" FOREIGN KEY ("salesPartnersId") REFERENCES "sales_partners"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_e253fbd572683bcc785a70cbca7" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_8c20bd83ab9df432718c8fe959d" FOREIGN KEY ("pricingId") REFERENCES "pricing"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9de9472d1a87fd106634222c1b8" FOREIGN KEY ("uomId") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_11690dede7681c3c9ec1fd62d08" FOREIGN KEY ("baseUomId") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_2a8ce0dd0205df008b9e2f09206" FOREIGN KEY ("serviceId") REFERENCES "services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_8f35adad8609a101b60013e008b" FOREIGN KEY ("nonStockServiceId") REFERENCES "non_stock_services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_notes" ADD CONSTRAINT "FK_ffbf174e0f2412a8352f4d7311b" FOREIGN KEY ("orderItemId") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item_notes" ADD CONSTRAINT "FK_bfa73e618c9695604eb53c24821" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "FK_780f48bc261cf77f68e27fbc38a" FOREIGN KEY ("purchaserId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchases" ADD CONSTRAINT "FK_ad30f79875fb64a6de23763bf42" FOREIGN KEY ("vendorId") REFERENCES "vendors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "services_items_items" ADD CONSTRAINT "FK_11e5c165b1866e0fe5dc2f5b178" FOREIGN KEY ("servicesId") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "services_items_items" ADD CONSTRAINT "FK_8d2d12b6b68b9da0d23b9aa72e3" FOREIGN KEY ("itemsId") REFERENCES "items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "items_services_services" ADD CONSTRAINT "FK_0af7ef64c6038062e767574dc88" FOREIGN KEY ("itemsId") REFERENCES "items"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "items_services_services" ADD CONSTRAINT "FK_d7864f4f5e2917fc23a6178ba73" FOREIGN KEY ("servicesId") REFERENCES "services"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "items_services_services" DROP CONSTRAINT "FK_d7864f4f5e2917fc23a6178ba73"`);
        await queryRunner.query(`ALTER TABLE "items_services_services" DROP CONSTRAINT "FK_0af7ef64c6038062e767574dc88"`);
        await queryRunner.query(`ALTER TABLE "services_items_items" DROP CONSTRAINT "FK_8d2d12b6b68b9da0d23b9aa72e3"`);
        await queryRunner.query(`ALTER TABLE "services_items_items" DROP CONSTRAINT "FK_11e5c165b1866e0fe5dc2f5b178"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "FK_ad30f79875fb64a6de23763bf42"`);
        await queryRunner.query(`ALTER TABLE "purchases" DROP CONSTRAINT "FK_780f48bc261cf77f68e27fbc38a"`);
        await queryRunner.query(`ALTER TABLE "order_item_notes" DROP CONSTRAINT "FK_bfa73e618c9695604eb53c24821"`);
        await queryRunner.query(`ALTER TABLE "order_item_notes" DROP CONSTRAINT "FK_ffbf174e0f2412a8352f4d7311b"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_8f35adad8609a101b60013e008b"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_2a8ce0dd0205df008b9e2f09206"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_11690dede7681c3c9ec1fd62d08"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9de9472d1a87fd106634222c1b8"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_8c20bd83ab9df432718c8fe959d"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_e253fbd572683bcc785a70cbca7"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_510af4fb2333c7184d568099aa3"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_e5de51ca888d8b1f5ac25799dd1"`);
        await queryRunner.query(`ALTER TABLE "payment_terms" DROP CONSTRAINT "FK_fc2ea9567ff5ab710909b61ec04"`);
        await queryRunner.query(`ALTER TABLE "payment_transactions" DROP CONSTRAINT "FK_318578310d536d61d1d94f87fe7"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_6af6faa4f594d828c7e9b784595"`);
        await queryRunner.query(`ALTER TABLE "commissions" DROP CONSTRAINT "FK_f5414c93004f4c88046110d9bd8"`);
        await queryRunner.query(`ALTER TABLE "commission_transactions" DROP CONSTRAINT "FK_f6fba111295cff46b676a143c0a"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_629d91468f5a76f4472c4909261"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_c59291c396d452f0c8e419d3e38"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_9a4ea23f9a8c1e130d7d4c1ddad"`);
        await queryRunner.query(`ALTER TABLE "items" DROP CONSTRAINT "FK_595a0c1018faf8f48c1ce36a280"`);
        await queryRunner.query(`ALTER TABLE "discounts" DROP CONSTRAINT "FK_bd1d07c0a61acb7b03cc195509a"`);
        await queryRunner.query(`ALTER TABLE "attribute" DROP CONSTRAINT "FK_3f57f0a2bd5fad53d34f1df877f"`);
        await queryRunner.query(`ALTER TABLE "uom" DROP CONSTRAINT "FK_999937e80f724f5a108f45af7bf"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_e6f608e57a5ea871bbec9aa3521"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_c642be08de5235317d4cf3deb40"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_a22cb8ff5a4d3709da216b11610"`);
        await queryRunner.query(`ALTER TABLE "sales_item_note" DROP CONSTRAINT "FK_fdacec9dee011f00cf271c0d98d"`);
        await queryRunner.query(`ALTER TABLE "sales_item_note" DROP CONSTRAINT "FK_3f31014ee602711ef7855df1dbc"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_bcfd467aaf89ac96018400368b7"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_b7b4a9fd8cc9efa37d2488084bc"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_8bafbb5d45827a5d25f5cd3c6f3"`);
        await queryRunner.query(`ALTER TABLE "purchase_items" DROP CONSTRAINT "FK_684a9853855f5edcd905dc2a9a8"`);
        await queryRunner.query(`ALTER TABLE "purchase_item_note" DROP CONSTRAINT "FK_71f033720e65d50b1fc466b5f4a"`);
        await queryRunner.query(`ALTER TABLE "purchase_item_note" DROP CONSTRAINT "FK_c8130ad301f2928a23ff2ca3697"`);
        await queryRunner.query(`ALTER TABLE "pricing" DROP CONSTRAINT "FK_399b0a2697e25f631095eaadd21"`);
        await queryRunner.query(`ALTER TABLE "pricing" DROP CONSTRAINT "FK_420e1792e18656a1d66a20bab0c"`);
        await queryRunner.query(`ALTER TABLE "pricing" DROP CONSTRAINT "FK_22aa7ee9e019f4f8bf61920da8c"`);
        await queryRunner.query(`ALTER TABLE "pricing" DROP CONSTRAINT "FK_bd8c383aa0df97a834c3fc77e83"`);
        await queryRunner.query(`ALTER TABLE "operator_stock" DROP CONSTRAINT "FK_f57c351323d17198f98203f7644"`);
        await queryRunner.query(`ALTER TABLE "operator_stock" DROP CONSTRAINT "FK_9f880821e14bcfc38e4fa152921"`);
        await queryRunner.query(`ALTER TABLE "user_machine" DROP CONSTRAINT "FK_531514348ce1804ff125735acbc"`);
        await queryRunner.query(`ALTER TABLE "user_machine" DROP CONSTRAINT "FK_7f74ce92adc1bdbd3e525fbe8b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7864f4f5e2917fc23a6178ba7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0af7ef64c6038062e767574dc8"`);
        await queryRunner.query(`DROP TABLE "items_services_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d2d12b6b68b9da0d23b9aa72e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11e5c165b1866e0fe5dc2f5b17"`);
        await queryRunner.query(`DROP TABLE "services_items_items"`);
        await queryRunner.query(`DROP TABLE "file_path"`);
        await queryRunner.query(`DROP TABLE "fixed_cost"`);
        await queryRunner.query(`DROP TABLE "vendors"`);
        await queryRunner.query(`DROP TABLE "purchases"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_roles_enum"`);
        await queryRunner.query(`DROP TABLE "order_item_notes"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TABLE "payment_terms"`);
        await queryRunner.query(`DROP TABLE "payment_transactions"`);
        await queryRunner.query(`DROP TABLE "sales_partners"`);
        await queryRunner.query(`DROP TABLE "commissions"`);
        await queryRunner.query(`DROP TABLE "commission_transactions"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "items"`);
        await queryRunner.query(`DROP TABLE "discounts"`);
        await queryRunner.query(`DROP TABLE "attribute"`);
        await queryRunner.query(`DROP TABLE "uom"`);
        await queryRunner.query(`DROP TABLE "sale_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f31014ee602711ef7855df1db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fdacec9dee011f00cf271c0d98"`);
        await queryRunner.query(`DROP TABLE "sales_item_note"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TABLE "purchase_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8130ad301f2928a23ff2ca369"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71f033720e65d50b1fc466b5f4"`);
        await queryRunner.query(`DROP TABLE "purchase_item_note"`);
        await queryRunner.query(`DROP TABLE "pricing"`);
        await queryRunner.query(`DROP TABLE "non_stock_services"`);
        await queryRunner.query(`DROP TABLE "services"`);
        await queryRunner.query(`DROP TABLE "operator_stock"`);
        await queryRunner.query(`DROP TABLE "unit_category"`);
        await queryRunner.query(`DROP TABLE "machine"`);
        await queryRunner.query(`DROP TABLE "user_machine"`);
    }

}
